queries = {
    "kvinna 1": ["kvinn*"],
    "Kvinna 2": [
        "änka*",
        "änke*",
        "dam",
        "damern*",  # "mina damer och herrar"
        "dotter*",
        "döttrar*",
        "flick*",
        "fröken*",
        "fröknar*",
        "fru",
        "fruntimmer*",
        "henne*",
        "henne*",
        "hon",
        "hustru*",
        "jungfru*",
        "mamma*",
        "mammor*",
        "moder",
        "moderns",
        "mödra*",
        "mor",
        "syster*",
        "systrar",
    ],  #
    # Work-related and possibly work-related titles
    "Kvinna 3": [
        "arbeterska*",
        "arbeterskor*",
        "dotter*",
        "döttrar*",
        "fabriksarbeterka*",
        "fabriksarbeterskor*",
        "fruntimmer*",
        "hembiträde*",
        "hushållerska*",
        "hushållerskor*",
        "kokerska*",
        "kokerskor*",
        "lärarinna*",
        "lärarinnor*",
        "mjölkerska*",
        "mjölkerskor*",
        "mödra*",
        "mor",
        "piga*",
        "pigor*",
        "sjuksköterska*",
        "sjuksköterskor*",
        "sköterska*",
        "sköterskor*",
        "småskolelärarinna*",
        "småskolelärarinnor*",
        "sömmerska*",
        "sömmerskor*",
        "tjänarinna*",
        "tjänarinnor*",
        "tjänsteflick*",
        "tjänstekvinna*",
        "tjänstekvinnor*",
        "tjänstepiga*",
        "tjänstepigor*",
        "uppaskerskor*",
        "uppasserska*",
    ],
}
